# Generated by Django 5.1.1 on 2024-09-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=100)),
                ('books_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
