# Generated by Django 5.1.1 on 2024-09-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS_app', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='books_img',
            new_name='book_img',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='books_name',
            new_name='book_name',
        ),
    ]
