# Generated by Django 5.1.1 on 2024-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS_app', '0003_rename_books_img_book_book_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='book_returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='book_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='number_of_books',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.IntegerField(),
        ),
    ]
