# Generated by Django 5.1.1 on 2024-09-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS_app', '0004_reader_book_returned_at_reader_book_taken_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book_returned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='book_taken_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
