# Generated by Django 5.1.1 on 2024-09-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS_app', '0005_alter_reader_book_returned_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='reference_id',
            new_name='card_no',
        ),
    ]
