# Generated by Django 5.1.1 on 2024-09-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS_app', '0006_rename_reference_id_reader_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='Books',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
