# Generated by Django 5.1.1 on 2024-09-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS_app', '0007_reader_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_address',
            field=models.CharField(max_length=100),
        ),
    ]
