# Generated by Django 5.1.1 on 2024-09-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS_app', '0008_book_about_book_author_alter_book_book_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='about',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_img',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_name',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
